services:
  - type: web
    name: CinemaAPI
    env: docker
    buildCommand: 'dotnet build'
    startCommand: 'dotnet CinemaAPI.dll'
    branch: master
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
